package-lock.json
package.json
test/requests.test.js
test/test-helper.test.js

- Move testing dependencies into devDependencies
- Globalize the common testing framework stuff
- Add sinon-chai for calledWith assertions
For the convenience functions in `platform-api/requests` we want to assert that the PlatformApi client was called a specific number of times  with specific payloads. You've covered the rest. I added `calledWith` coverage on `getSchema`. Same could be done for `bibById`. I'd also suggest a slightly more involved test could be added for the less trivial `bibsForItems` and `bibsForHoldings` functions, where we want to assert that `client.get` is called a specific number of times, with a predictable set of playloads. I think this can be done with `callCount` and several `calledWith` assertions (See [here for …

A couple small improvments to tests

---

lib/sierra-models/base.js
test/fixtures/bib-parallels-chaos.json
test/unit/sierra-base.test.js

Some proposals to:
- fix orphaned parallel extraction, which wasn't handled properly before (parallel values were taking the place of primary values)
- refactor the "prettify" function for clarity
- add tests to cover some contrived edge cases with orphaned parallels

Refactoring and fixing orphaned parallel extraction

---

lib/mappings/mappings.js
lib/utils/primary-and-parallel-values.js
test/unit/es-bib.test.js
test/unit/mappings.test.js
test/unit/primary-and-parallel-values.test.js

- When `*Mappings.get` is called with a bib, the `mappings` lookup should not be modified for subsequent calls
- Ensure missing primary values are rendered as ''
- `*Mappings.get` methods should return an array of marc queries

A few small fixes to parallel/primary extraction:

---

lib/platform-api/client.js
lib/platform-api/requests.js
lib/scsb/client.js
lib/utils/m2-customer-codes.js
test/unit/index.test.js
test/unit/m2-customer-codes.test.js
test/unit/platform-api-client.test.js
test/unit/platform-api-requests.test.js
test/unit/to-json.test.js
test/unit/utils.js

This PR incorporates m2 customer code lookups to the indexing process. Largely copied from Paul's work, with an addition for handling a response without a 200 code. @nonword you might want to include something like that in the DHI as well. I'm not sold that this implementation is the move, but there definitely has to be something checking for response.data because 404 responses do not have a data property.
Also tests!

Scc 3422/add m2 indexing

---

lib/es-models/bib.js
lib/es-models/checkin-card-item.js
lib/es-models/holding.js
lib/es-models/item.js
lib/general-prefetch.js
lib/mappings/bib-mapping.json
lib/mappings/holding-mapping.json
lib/platform-api/requests.js
lib/scsb/requests.js
lib/sierra-models/base.js
lib/sierra-models/bib.js
lib/sierra-models/holding.js
lib/to-json.js
lib/utils.js
lib/utils/item-date-parse-preparsing-objects.js
lib/utils/item-date-parse.js
scripts/compare-with-indexed.js
test/unit/es-bib.test.js
test/unit/es-checkin-card-item.test.js
test/unit/es-holding.test.js
test/unit/es-item-test.js
test/unit/index.test.js
test/unit/primary-and-parallel-values.test.js
test/unit/sierra-base.test.js
test/unit/utils-checkin-card-date-parse.test.js
test/unit/utils-test.js

EsItem:
- Implement `EsItem.formatLiteral`
- Ensure LCCNs are included in identifiers
- Ensure ES model methods that return `null` are not included in to-json
- Fix `idOclc` implementation
- Fix `EsItem.aeonUrl` implementation
EsBib:
- Fix bug relating holdings
- Add `dateString`
- Add `numCheckinCardItems`, `numItemDatesParsed`, `numItemVolumesParsed`, and `numItemsTotal`
- Add " -- " joiner to `subjectLiteral` mapping
EsCheckinCardItem
- Fix `formatLiteral`
EsHolding
- Fix `holdingStatement`
- Change `location.id` to `location.code`
- Ensure `checkinBoxes` is sorted by `position`
Also 
- Expands test coverage in a few areas
- Alphabetizes `EsItem` and `EsBib` methods (sorry)
- Fixes compare-with-indexed script, broken by recent changes to build-es-document
- Adds item date parsing (and …

SCC-3580: Fix a few small indexing issues

---

lib/es-models/bib.js
lib/es-models/checkin-card-item.js
test/unit/es-checkin-card-item.test.js

Fix bug where extracted checkin card formatLiteral try to use holding fieldtag i (probably because EsHolding.format does that?). But I don't think this is correct; EsCheckinCardItem.formatLiteral should instead fall back on EsBib.materialType to replicate what DFE has been doing.

Fix indexing bug in EsCheckinCardItem.formatLiteral

---

lib/es-models/item.js
lib/sierra-models/base.js

Fixes some small issues that have come up while running the DHI tester. Mostly adds some extra defensive programming, but also a couple of places where types are wrong 
1. It seems `noteContent` is of the form `{value: string}` not `string`
2. It seems baseAeonUrl is of the form `[string]` not `string`
We should probably hold off on merging this until the bugs are fully sorted out

Fix small bugs

---

lib/elastic-search/requests.js
lib/es-models/bib.js
lib/platform-api/requests.js
lib/utils/nypl-source-mapper.js
lib/utils/uriForRecordIdentifier.js
scripts/compare-with-indexed.js
scripts/reindex-record.js
test/fixtures/bib-11606020.json
test/unit/es-bib.test.js
test/unit/platform-api-requests.test.js

We noticed a stubbed function that never got un-stubbed. Mostly copied functions from discovery-api-indexer.

replace stub

---

lib/elastic-search/requests.js
lib/es-models/base.js
lib/es-models/bib.js
lib/es-models/checkin-card-item.js
lib/es-models/holding.js
lib/es-models/item.js
lib/platform-api/client.js
lib/platform-api/requests.js
lib/sierra-models/base.js
lib/utils.js
lib/utils/m2-customer-codes.js
lib/utils/suppressBibs.js
lib/utils/volume-parse.js
scripts/compare-with-indexed.js
test/unit/elastic-search-requests.test.js
test/unit/es-holding.test.js

- Minor indexing fixes to:
- EsHolding.notes
- EsBib.identifierV2 (cancelled/invalid ISBN & ISSN)
- Fix bug in suppressRecord
- Better debug log messages in a few places
- Better display of indexing errors when some but not all failed
- In compare-with-indexed, don't fail hard if live document isn't found.

Additional cleanup

---

lib/elastic-search/requests.js
lib/es-models/base.js
lib/es-models/bib.js
lib/es-models/checkin-card-item.js
lib/es-models/holding.js
lib/es-models/item.js
lib/mappings/mappings.js
lib/platform-api/client.js
lib/platform-api/requests.js
lib/sierra-models/base.js
lib/utils.js
lib/utils/m2-customer-codes.js
lib/utils/primary-and-parallel-values.js
lib/utils/suppressBibs.js
lib/utils/volume-parse.js
scripts/compare-with-indexed.js
test/unit/elastic-search-requests.test.js
test/unit/es-holding.test.js
test/unit/primary-and-parallel-values.test.js
test/unit/sierra-base.test.js

- We now dedupe VarFieldMatch objects returned from
SierraBase.varFieldsMulti calls (previously only applied to
individual SierraBase.varField calls)
- The de-duping goes to extra effort to identify and remove any
orphaned parallel that is redundant because another
VarFieldMatch entry exists with that same value that is also attached
to a primary value. (Also makes same check for orphaned primaries.
Fixes handling excludedSubfields property of mappings by ensuring that
mapping entries are cast into the proper MarcQuery structure (i.e. put
excludedSubfields into a mappingOptions hash). This bug was causing, for
example, contributorLiteral mappings to add $0 to values because the
excludedSubfields option was being ignored.

Scc 3680 addtl

---

lib/es-models/item.js
lib/scsb/requests.js
lib/utils.js
lib/utils/aeon-urls.js
test/fixtures/bib-22027953.json
test/fixtures/item-37528709.json
test/unit/platform-api-requests.test.js
test/unit/utils-aeon-urls.test.js
test/unit/utils-test.js
test/unit/utils.js

No longer require or use bib 856 when building Aeon URLs. Build URL entirely from item and bib data when valid site code is found in item fieldTag x. This is the new way we'd like to build Aeon URLs. The Aeon URLs will differ from the existing 856 sourced URLs in (it is hoped) insignificant ways.
Also centralizes nypl-source-mapper stubbing since a lot of tests will trigger it.

Change method for building Aeon URLs

---

lib/build-es-document.js
lib/prefilter.js
lib/sierra-models/bib.js
lib/sierra-models/item.js
lib/utils/locations.js
scripts/compare-with-indexed.js
test/fixtures/bib-18101449.json
test/unit/index.test.js
test/unit/prefilter.test.js
test/unit/sierra-bib.test.js
test/unit/sierra-item.test.js
test/unit/utils-locations.test.js

Incorporate suppression and is-research checks
- Add isResearch and supporting methods to Sierra models to ensure we
don't index Circ records
- Reorganize build-es-document to ensure we apply is-research and
suppression checks on bibs regardless of the original event type
- Update compare-with-indexed script to add support for holding ids and
inumbers

Noref fix suppression of non research

---

scripts/reindex-record.js

- Addresses bug where NYPL Source Mapper was not being accessed by the correct path
- updates reindex script to properly use .then()

fix async issue

---

lib/es-models/item.js
lib/utils.js
lib/utils/aeon-urls.js
test/unit/utils-aeon-urls.test.js
test/unit/utils-test.js

By request, adding a new ItemVolume= param to Aeon URLS to hold volume information. (Removing it from CallNumber)

Add ItemVolume to aeon URL

---

.travis.yml
lib/utils/volume-parse.js
test/unit/utils-volume-parse.test.js

Fixes production issue where a parsed volume exceeds integer range, leading to a ES write error. Adds full set of tests for volume parsing.
Also removes `.travis.yml` because we rely on gh actions for tests.

Fix issue excluding volumeRanges beyond int bounds

---

lib/sierra-models/base.js
test/fixtures/bib-pul-99122517373506421.json
test/unit/es-bib.test.js

Notes with 1st indicator '0' should be suppressed. When they're suppressed, `_convertRawFieldToVarFieldMatch` returns `null`, but we then tried to attach a `.script` property to the VarFieldMatch object, creating a runtime error

Fix bug handling bib with suppressed note

---

lib/utils/locations.js
test/unit/sierra-item.test.js
test/unit/utils-locations.test.js

Updates the location prefix check to ensure that we assume items in any "rc" prefixed location are ReCAP even if we don't yet have them in NYPL-Core.
Also adds several tests to improve coverage of the `getIsResearchWithRationale` call.

Fix bug identifying newer rc locations as Research

---

index.js
lib/utils/aeon-urls.js
test/unit/index.test.js
test/unit/utils-aeon-urls.test.js

Fixes a bug that came up testing Aeon links in QA. When building the `Title` param for Aeon links, we weren't expecting orphaned parallels. This fixes that (and opts to use the parallel value over the primary when it exists).

Fix aeon bug

---

lib/es-models/bib.js
test/unit/es-bib.test.js

- Changes the way we check whether CheckinCards have an Offsite location to allow for `null` locations
- Changes tests to match the new code

Add check for holdings with null location

---

lib/utils/aeon-urls.js
test/unit/utils-aeon-urls.test.js

Previously we were using Bib fixed field 'Material Type' label. We're asked to use item fixed field 'Item Type' label instead.

Change Aeon Genre param to Item Type label

---

lib/es-models/bib.js
test/unit/es-bib.test.js

Fix production bug encountered in partner record. Indexer assumed a 337 would have primary content, whereas some only have parallel content and should be ignored.

Noref fix mediatype bug

---

lib/utils/aeon-urls.js
test/unit/utils-aeon-urls.test.js

Use 260 $bc and 264 $bc for Aeon ItemPublisher. (Previously ignored $c.)
https://jira.nypl.org/browse/SCC-4046

Change Aeon URL: Add $c to ItemPublisher

---

lib/elastic-search/index-schema.js
lib/elastic-search/requests.js
lib/es-models/bib.js
lib/utils/author-names.js
scripts/bulk-index.js
scripts/compare-with-indexed.js
scripts/utils.js
test/unit/es-bib.test.js
test/unit/scripts-mapping-check.test.js
test/unit/utils-author-names.test.js

Adds a couple new ES fields to improve author matching.
Also fixes a couple minor things with bulk-index and compare-with-indexed scripts.
~This depends on Node20 updates, so targets that branch currently, but will be merged into `main` when which are now in `main` since [PR 89](https://github.com/NYPL/research-catalog-indexer/pull/89) is merged.~

A few added fields for ES tuning

---

.github/workflows/test-and-deploy.yml
lib/elastic-search/index-schema.js
lib/es-models/bib.js
lib/platform-api/requests.js
provisioning/base/resources.tf
sam.local.yml

Fix a few minor things uncovered when validating qa deployment:
- Use Node20 (not 18) everywhere
- Note the new `popularity` property in the index-schema (mostly a formality)
- Fix small runtime bug with checkin cards
- Job should error hard when encountering unrecoverable platform api auth errors

Fix a few things uncovered in testing

---

lib/es-models/bib.js
lib/utils/author-names.js
test/fixtures/bib-10027451.json
test/unit/es-bib.test.js
test/unit/utils-author-names.test.js

Updates contributorLiteralNormalized and contributorLiteralWithoutDates fields to remove entries that are found to duplicate creator* fields.
This is to ensure we don’t ever have a bib with, for example, creatorLiteralNormalized "Charles Dickens" and contributorLiteralNormalized "Charles Dickens" due to the two different Charles's being named in different roles, which would unfairly boost this record when matching on both of those Normalized fields.
Also adds removal of trailing period characters in creator and contributor fields so that we don't ever index e.g. "Dickens, Charles.".
https://newyorkpubliclibrary.atlassian.net/browse/SCC-4278

Ensure contributor* fields don't duplicate creator*

---

lib/es-models/bib.js
test/unit/es-bib.test.js

Being an array of distinct parent location ids for the bib's items, so that we can boost on-site materials and filter by research center.
https://newyorkpubliclibrary.atlassian.net/browse/SCC-4279

Add EsBib.buildingLocationIds

---

lib/mappings/bib-mapping.json
test/unit/es-bib.test.js

For https://newyorkpubliclibrary.atlassian.net/browse/SCC-4478 - this adds Biographical expansion to the searchable fields in the index.

[SCC-4478] Add 545b to index mapping for bib

---

lib/elastic-search/requests.js
scripts/identify-ids-by-es-query.js
scripts/identify-ids-by-query.js

A script for building a CSV of bib ids for an arbitrary ES query. Useful for building a CSV of records for feeding into the RCI bulk-index script.

Add identify-ids-by-es-query script

---

lib/es-models/item.js
test/unit/es-item.test.js

By popular demand, stop adding fieldtag v to shelfmark.
https://newyorkpubliclibrary.atlassian.net/browse/SCC-4590

Stop adding fieldtag v to shelfMark

---

index.js
lib/browse-terms/index.js
test/unit/browse-term.test.js

- filter out non research bibs from bib subject parsing activity
- add bib id prefix to sourceId
- move subject parsing to after RCI bib deletions happen. I don't think this makes a huge difference, but an effort to ensure that subject bib counts are definitely made after bibs are deleted.

filter non research;add source prefix for subjects

---

lib/es-models/bib.js
package-lock.json
package.json

Use updated browse term package to trim whitespace, and remove it from the RCI

rely on trim from browse-terms

---

lib/utils/volume-parse.js
test/unit/utils-volume-parse.test.js

perhaps there is other work to be done to make this better... I'm parsing box numbers and then flipping them numerically to force an ascending sort. This really only helps when there are a majority of records with boxes. it does not make anything better or worse for a record like [this one](https://www.nypl.org/research/research-catalog/bib/b15059124). however, the heterogeneous nature of the metadata indicates to me that we should not be attempting to mechanically sort these, but rather finding a way to honor item sort from sierra.

add box to enumeration chronology parsing

---

lib/es-models/bib.js
lib/utils/es-ranges.js
test/unit/es-bib.test.js

Fixes a big where the `dates.raw` field was being indexed as an object, whereas ES expects a string.
Also fixes tests.

Fix bug so that dates.raw will be a string

---

lib/browse-terms/index.js
lib/elastic-search/requests.js
lib/es-models/bib.js
package-lock.json
package.json
test/fixtures/browse-term-fixtures.js
test/unit/browse-term.test.js
test/unit/es-bib.test.js

- branch logic to allow for special handling of bibs when we are ingesting
- when we are populating a browse term from scratch, there is no concern about counts for old subjects being out of date. we only need to send freshly generated subjects to the BTI
- in other indexing cases, we only need to send any diff between the currently indexed live bib and the newly generated subject literals (ie OUTER EXCLUDING JOIN in SQLese)
- extra filtering of potentially doubled subjects
This is a departure from original thinking, which was to send all subjects to BTI and not make any determinations as to what should be indexed. Limiting stress on the resources index requires intervention here because by the time data is at the BTI, we no longer have access to any bib relationships
Tests are broken …

Noref enforce term diffs

---

index.js
lib/browse-terms/index.js
test/unit/index.test.js

This PR includes:
- creating diff of new subjects generated and existing subjects in resources index, instead of sending all new and live subjects
- conditionally skipping this check if optional flag for ingest is true, in which case we want to just send only the new subjects
- a fix for a bug introduced from the above changes:
- generate the subject events before writes/deletes to the resources index, 
- send them to the sqs stream after writes/deletes to the resources index.
I tested the bugfix by:
1. reindexing 20 bibs with the existing code (building diff and sending subject events before resources updates), adding an additional " spaghetti"  to every subject. (addition was to ensure that subjects and counts would be brand new)
- On some, I was getting zero counts in the BTI logs. …

Subject diffs and off by one fix

---

lib/es-models/bib.js
lib/utils/es-ranges.js
test/unit/es-bib.test.js

Some changes that came out of discussions following our initial QA indexing of partner records:
- Make date type 'm' a date range
- Add throwing error for invalid dates (currently we are returning `null` which causes an uncaught error in a small number of cases. Purposely throwing an `InvalidDateError` when dates fail validation is more semantically correct and allows us to catch the error in the parent block)
- Fix/add tests

Make date type 'm' a range + small fixes
